### ISSUE TITLE
Token handling 

### ISSUE THREAD

**Issue by dend** [SpartanReport/SpartanReport#20]
I did a cursory check over the code to see how you're handling tokens/auth. It does seem like the authentication is _mostly_ done server-side in the Go implementation. I am not a Go expert, so I had to extrapolate some of the findings based on my understanding of the code.

First, I am not entirely sure if you even need server-side token handling. You could use a **public client** application (don't need a secret) that is your frontend. It can authenticate the user and perform the same dance to get the Spartan token (e.g., that's what Halo Waypoint does). Unless you expect to be performing server-side modifications without the user's presence, that should suffice.

Second, I do wonder where the tokens go server-side. Are you storing them in-memory? It _seems_ like it, but I am not entirely sure. Mainly concerned with [4.5.2 of the OAuth 2.0 Threat Model and Security Considerations
](https://www.rfc-editor.org/rfc/rfc6819#section-4.5.2) document. Refresh tokens are _highly confidential_ due to their ability to mint new access tokens.

**Comment by SpartanReport** [comment]
I think the right path to properly handling authentication would be to transition to a public client application. To be frank, I'm not very familiar with react + MSAL. 

They are being currently stored in memory as it stands. I can remove the refreshing process until the authentication work can be transitioned to client side instead. It won't be nice having to manually sign in after a token expires again, but it should mitigate that risk

**Comment by SpartanReport** [comment]
merged #21

**Comment by SpartanReport** [comment]
Done - Merged into main, feel free to reopen/ping for any other comments/concerns 😃

**Comment by dend** [comment]
Awesome - I think going down the public client application route is the right approach for what you are trying to do, and then store the tokens through the browser like other web apps. @SpartanReport
